"""RUTAS DE LOS FICHEROS DEL PROYECTO"""
BASE_ROOT = "resources/"

FILES_ROOT = BASE_ROOT + "files/"
LOCAL_ROOT = BASE_ROOT + "local/"
REMOTE_ROOT = BASE_ROOT + "remote/"

LOCAL_SIGNNED = LOCAL_ROOT + "signned/"
LOCAL_ENCRYPTED = LOCAL_ROOT + "encrypted/"
LOCAL_DECRYPTED = LOCAL_ROOT + "decrypted/"

REMOTE_SIGNNED = REMOTE_ROOT + "signned/"
REMOTE_UPLOADS = REMOTE_ROOT + "uploads/"
REMOTE_DOWNLOADS = REMOTE_ROOT + "downloads/"

REMOTE_DOWNLOADS_ENC = REMOTE_DOWNLOADS + "encrypted/"
REMOTE_DOWNLOADS_DEC = REMOTE_DOWNLOADS + "decrypted/"
