kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: c1
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 30000 # Set to 80 if using Ingress
      hostPort: 30000 # Set to 80 if using Ingress
      protocol: TCP