# Generated by Django 3.2.6 on 2022-06-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('modelo1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.modelo1')),
            ],
        ),
    ]
